### ISSUE TITLE
Infinite rotation axes 

### ISSUE THREAD

**Issue by kovalp** [abelcarreras/posym#3]
First of all, I enjoyed the package a lot. I started my derivative of it in order to split the package into smaller pieces and achieve a pure Python software.

Second, I would be nice to have links to the theory of the method mentioned in the Readme.

Would this be https://pubs.acs.org/doi/pdf/10.1021/ja00046a033 ? Or there are better references?

Finally for this issue, forgive my eventual ignorance, but are the infinite rotation axes analysable within the method of continuous symmetry measures? 

I could not analyse the group D*h (D∞h). I guess there is a difficulty related to this group.

Is it possible to detect this symmetry in the method? Is it possible to apply this symmetry group to the normal mode analysis?

**Comment by abelcarreras** [comment]
Hi @kovalp, I'm glad you liked this library.

Indeed, the reference you suggest is a good starting point. Other useful references can be found here:
https://cosymlib.readthedocs.io/introduction.html

and more recent ones:

Pinsky M, Dryzun C, Casanova D, Alemany P, Avnir D, J Comput Chem. 29:2712-21 (2008) 
Pinsky M, Casanova D, Alemany P, Alvarez S, Avnir D, Dryzun C, Kizner Z, Sterkin A. J Comput Chem. 29:190-7 (2008)
Casanova D, Alemany P. Phys Chem Chem Phys. 2010;12(47):15523–9.
Casanova D, Alemany P, Falceto A, Carreras A, Alvarez S. J Comput Chem 2013;34(15):1321–31.

Regarding the linear groups, they are not implemented at this time.
I don't see any reason why linear groups should not be analyzable using CSM, however the implementation is quite 
tough to do and I haven't found a good way yet.

**Comment by abelcarreras** [comment]
To detect symmetry (get point symmetry group) you have to use another library. Posym is not designed for this,
since the point is to be able to work with any molecule with any point group. Of course you can try to measure
all groups and check which one gives CSM =0 but this is quite inefficient. 
For symmetry detection I wrote this library some time ago that uses the classic method using the inertia tensor.
if you are interested: https://github.com/abelcarreras/pointgroup 

Alternatively I think pymatget also has a symmetry analysis module.

**Comment by abelcarreras** [comment]
Also if you want to write a pure python version. You basically just have to replace these functions:

product_poly_coeff, gaussian_integral, gaussian_integral_2

by its pure-python version in the basis.py file, which are written in the same file. 
However this will slow down the code quite a lot.

**Comment by kovalp** [comment]
> 

I have found your repository https://github.com/abelcarreras/pointgroup and I am aware that the pymatgen offers detection of point-group symmetries. However, I don't know how to apply this to the analysis of normal modes. 

An example of this problem would be very nice to have.

**Comment by kovalp** [comment]
> Hi @kovalp, I'm glad you liked this library.
> 
> Indeed, the reference you suggest is a good starting point. Other useful references can be found here: https://cosymlib.readthedocs.io/introduction.html
> 
> and more recent ones:
> 
> Pinsky M, Dryzun C, Casanova D, Alemany P, Avnir D, J Comput Chem. 29:2712-21 (2008) Pinsky M, Casanova D, Alemany P, Alvarez S, Avnir D, Dryzun C, Kizner Z, Sterkin A. J Comput Chem. 29:190-7 (2008) Casanova D, Alemany P. Phys Chem Chem Phys. 2010;12(47):15523–9. Casanova D, Alemany P, Falceto A, Carreras A, Alvarez S. J Comput Chem 2013;34(15):1321–31.
> 
> Regarding the linear groups, they are not implemented at this time. I don't see any reason why linear groups should not be analyzable using CSM, however the implementation is quite tough to do and I haven't found a good way yet.

The library cosymlib seems to be nice and I did not find it using Google. Thanks for pointing it out!
The page [introduction.html](https://cosymlib.readthedocs.io/introduction.html) does not exist though.

**Comment by kovalp** [comment]
> Also if you want to write a pure python version. You basically just have to replace these functions:
> 
> product_poly_coeff, gaussian_integral, gaussian_integral_2
> 
> by its pure-python version in the basis.py file, which are written in the same file. However this will slow down the code quite a lot.

Right. I figured that. Everything is already in the repo. I find this very nice.

**Comment by kovalp** [comment]
This issue is a mix of several things. I would create 3 issues out of it. Do you want me to do it?

**Comment by abelcarreras** [comment]
> This issue is a mix of several things. I would create 3 issues out of it. Do you want me to do it?

Nah! don't worry, its fine

**Comment by abelcarreras** [comment]
> I have found your repository https://github.com/abelcarreras/pointgroup and I am aware that the pymatgen offers detection of point-group symmetries. However, I don't know how to apply this to the analysis of normal modes.
> 
> An example of this problem would be very nice to have.

To analyze the symmetry of the normal modes you just need to determine the point group of the molecule using for example pointgroup library and then use posym to get the symmetry of the different modes as the example in the README.
I plan to write the proper documentation of posym in the near future but I didn't have time sorry. I will try at least to include some more examples

**Comment by kovalp** [comment]
More examples would be nice indeed.
