### ISSUE TITLE
Troubles with water.

### ISSUE THREAD

**Issue by kovalp** [abelcarreras/posym#4]
The water molecule has the point group symmetry C2v. https://www.chemtube3d.com/sym-waterc2v/

However, if I analyse using the following script

```
from posym import SymmetryMoleculeBase

coordinates = [[0.00000, 0.0000000, -0.0808819],
               [-1.43262, 0.0000000, -1.2823700],
               [1.43262, 0.0000000, -1.2823700]]

symbols = ['O', 'H', 'H']


def analyse_geometry() -> None:
    """."""
    for group in ('Td', 'C2v', 'C3v', 'C4v'):
        sym_geom = SymmetryMoleculeBase(group=group, coordinates=coordinates, symbols=symbols)
        print(f'Symmetry measure {group}: ', sym_geom.measure)


if __name__ == '__main__':
    analyse_geometry()
```

I get the largest weight on Td and zero! weight on C2v:

```
>> python posym_test.py 
Symmetry measure Td:  62.39356218748866
Symmetry measure C2v:  0.0
Symmetry measure C3v:  18.992456339028262
Symmetry measure C4v:  18.992456339028262

```

I interpret that `posym`  suggests that Td would be the symmetry group of water. Is this correct interpretation? How to analyse and get the textbook symmetry group?

**Comment by abelcarreras** [comment]
The usual definition of continuous symmetry measures CSM (sym_geom.measure ) is this:
CSM = (1- S)*100
were S is the projection over the most symmetric irreducible representation of the group.
This corresponds more or less to the average overlap of all symmetry operations of the group. 

Therefore if the molecule has symmetry of the group CSM will be zero, and it will increase as the molecule
gets distorted and gets far from the symmetry of the group. This is why you get CSM = 0 for C2v group.

**Comment by kovalp** [comment]
I see. It would be nice to explain this in the example, if you want.
