### ISSUE TITLE
Repetitive operations for Hungarian permutations

### ISSUE THREAD

**Issue by kovalp** [abelcarreras/posym#6]
https://github.com/abelcarreras/posym/blame/7fcd03419d52110510c92aa14cd44c3076cea598/posym/operations/__init__.py#L79

The list of arrays sub_matrices_indices could be computed just once and cached.

I  got this to work here
https://github.com/kovalp/posym-normal-modes/blob/master/src/posym_normal_modes/permutations.py

It brings a factor 1.5 speedup.

**Comment by abelcarreras** [comment]
Thanks I will check!

**Comment by abelcarreras** [comment]
done
